image: docker:latest
services:
  - docker:dind
stages:
  - build_push
  - deploy
variables:
  DOCKER_DRIVER: overlay
  DOCKER_IMAGE_DEV: registry.gitlab.com/a-value/dev/7-days/api/dev:latest
  DOCKER_IMAGE_PROD: registry.gitlab.com/a-value/dev/7-days/api/prod:latest
  CAPROVER_APP: 'seven-days-better-you-api'

build_push_dev:
  stage: build_push
  only:
    - deploy
  script:
    - docker build --build-arg API_ENV="development" -t $DOCKER_IMAGE_DEV  .
    - echo $DOCKER_PASSWORD | docker login registry.gitlab.com -u $DOCKER_ID --password-stdin
    - docker push $DOCKER_IMAGE_DEV

deploy_dev:
  stage: deploy
  only:
    - deploy
  script:
    -  docker run caprover/cli-caprover:v2.1.1 caprover deploy --caproverUrl $CAPROVER_URL --caproverPassword $CAPROVER_PASSWORD --caproverApp $CAPROVER_APP --imageName $DOCKER_IMAGE_DEV

